import { useState, type MouseEvent } from "react";
import logo from "../../img/neuroflux_logo_transparente.png";
import { canManage, type User } from "../../lib/api";
type Props = { user: User | null; openAuth: (mode?: "login" | "register") => void; logout: () => void };
export function Header({ user, openAuth, logout }: Props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const goTo = (id: string) => (event: MouseEvent<HTMLAnchorElement>) => { setMenuOpen(false); if (window.location.pathname !== "/") return; event.preventDefault(); document.querySelector(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); window.history.replaceState({}, "", id); };
  const links = <><a href="/#inicio" onClick={goTo("#inicio")}>Início</a><a href="/#sobre" onClick={goTo("#sobre")}>Sobre</a><a href="/#beneficios" onClick={goTo("#beneficios")}>Benefícios</a><a href="/#series" onClick={goTo("#series")}>Séries</a><a href="/#como-funciona" onClick={goTo("#como-funciona")}>Como funciona</a>{user && <><a href="/materiais" onClick={() => setMenuOpen(false)}>Materiais</a><a href="/calendario" onClick={() => setMenuOpen(false)}>Calendário</a></>}{canManage(user) && <a href="/painel" onClick={() => setMenuOpen(false)}>Painel</a>}</>;
  return <header className="navbar"><nav><a className="brand" href="/"><img src={logo} alt="Neuroflux" /></a><div className="nav-links">{links}</div>{user ? <div className="session-actions"><div className="user-greeting"><span>Olá, </span><strong>{user.name.split(" ")[0]}</strong></div><button className="sign-out" onClick={logout} aria-label="Sair da conta" title="Sair"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 4H5.8A1.8 1.8 0 0 0 4 5.8v12.4A1.8 1.8 0 0 0 5.8 20H10M12 8l4 4-4 4M16 12H8" /></svg></button></div> : <div className="guest-actions"><button className="nav-cta" onClick={() => openAuth("login")}>Entrar</button></div>}<button className={`menu-toggle ${menuOpen ? "open" : ""}`} onClick={() => setMenuOpen(open => !open)} aria-label={menuOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={menuOpen}><span /><span /><span /></button></nav><div className={`mobile-menu-backdrop ${menuOpen ? "open" : ""}`} onClick={() => setMenuOpen(false)} /><aside className={`mobile-menu ${menuOpen ? "open" : ""}`} aria-hidden={!menuOpen}><div className="mobile-menu-header"><img src={logo} alt="Neuroflux" /><button onClick={() => setMenuOpen(false)} aria-label="Fechar menu">×</button></div><div className="mobile-menu-links">{links}</div><div className="mobile-menu-account">{user ? <><p>Conectado como <strong>{user.name}</strong></p><button className="mobile-logout" onClick={() => { setMenuOpen(false); logout(); }}>Sair da conta</button></> : <button className="button button-primary" onClick={() => { setMenuOpen(false); openAuth("login"); }}>Entrar ou criar conta</button>}</div></aside></header>;
}
