import { useEffect, useMemo, useState, type FormEvent } from "react";
import { apiUrl, token, type CalendarEvent, type EventType, type User } from "../../lib/api";
import { useCrudFeedback } from "../../components/feedback/CrudFeedback";

type Props = { user: User | null; openAuth: (mode?: "login" | "register") => void };
const labels: Record<EventType, string> = { EVENT: "Eventos", ENTRANCE_EXAM: "Vestibulares", OLYMPIAD: "Olimpíadas" };
const filters: Array<EventType | "ALL"> = ["ALL", "EVENT", "ENTRANCE_EXAM", "OLYMPIAD"];
const weekdays = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];
const dateKey = (date: Date | string) => { const value = typeof date === "string" ? new Date(date) : date; return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; };
const when = (date: string) => new Date(date).toLocaleString("pt-BR", { dateStyle: "medium", timeStyle: "short" });
const toInput = (date: string | null) => date ? new Date(date).toISOString().slice(0, 16) : "";

export function CalendarPage({ user, openAuth }: Props) {
  const { track } = useCrudFeedback();
  const [filter, setFilter] = useState<EventType | "ALL">("ALL");
  const [events, setEvents] = useState<CalendarEvent[]>([]);
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<CalendarEvent | null>(null);
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selectedDay, setSelectedDay] = useState(() => new Date());
  const load = async () => { if (!user) return; setMessage("Carregando calendário…"); try { const response = await fetch(`${apiUrl}/api/events${filter === "ALL" ? "" : `?type=${filter}`}`, { headers: { Authorization: `Bearer ${token()}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setEvents(data); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível carregar o calendário."); } };
  useEffect(() => { void load(); }, [filter, user]);
  const byDay = useMemo(() => events.reduce<Record<string, CalendarEvent[]>>((days, event) => { const key = dateKey(event.startsAt); (days[key] ??= []).push(event); return days; }, {}), [events]);
  const selectedEvents = byDay[dateKey(selectedDay)] ?? [];
  if (!user) return <main className="calendar-page gated-page"><section className="access-card"><p className="eyebrow">CALENDÁRIO</p><h1>Organize seus próximos passos.</h1><p>Entre para consultar eventos, vestibulares e olimpíadas.</p><button className="button button-primary" onClick={() => openAuth("login")}>Entrar</button></section></main>;
  const remove = async (item: CalendarEvent) => { if (!window.confirm(`Excluir “${item.title}”?`)) return; try { const response = await track(fetch(`${apiUrl}/api/events/${item.id}`, { method: "DELETE", headers: { Authorization: `Bearer ${token()}` } })); if (!response.ok) throw new Error(); setEvents(old => old.filter(event => event.id !== item.id)); } catch { setMessage("Não foi possível excluir o item."); } };
  return <main className="calendar-page"><section className="calendar-hero"><p className="eyebrow">AGENDA NEUROFLUX</p><h1>Calendário de oportunidades</h1><p>Acompanhe eventos, vestibulares e olimpíadas em um só lugar.</p></section><section className="calendar-content"><div className="calendar-tabs" role="tablist">{filters.map(item => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item === "ALL" ? "Todos" : labels[item]}</button>)}</div><MonthCalendar month={month} events={byDay} selectedDay={selectedDay} onMonthChange={setMonth} onSelect={setSelectedDay} />{message && <p className="library-status">{message}</p>}<section className="day-agenda"><div><p className="eyebrow">AGENDA DO DIA</p><h2>{selectedDay.toLocaleDateString("pt-BR", { weekday: "long", day: "numeric", month: "long" })}</h2></div><div className="day-events">{!message && selectedEvents.length === 0 && <p>Nenhum compromisso neste dia.</p>}{selectedEvents.map(item => <article className="day-event" key={item.id}><span className={`event-tag ${item.type.toLowerCase()}`}>{labels[item.type]}</span><div><h3>{item.title}</h3><p>{item.description}</p><small>{when(item.startsAt)}{item.location ? ` · ${item.location}` : ""}</small>{item.link && <a className="text-link" href={item.link} target="_blank" rel="noreferrer">Mais informações <span>→</span></a>}</div>{user.role === "MASTER" && <div className="event-actions"><button className="plain-button" onClick={() => setEditing(item)}>Editar</button><button className="danger-button" onClick={() => void remove(item)}>Excluir</button></div>}</article>)}</div></section>{user.role === "MASTER" && <section className="event-manager"><div><p className="eyebrow">GESTÃO DO MASTER</p><h2>{editing ? "Editar item" : "Adicionar ao calendário"}</h2></div><EventForm editing={editing} defaultDate={dateKey(selectedDay)} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); void load(); }} /></section>}</section></main>;
}

function MonthCalendar({ month, events, selectedDay, onMonthChange, onSelect }: { month: Date; events: Record<string, CalendarEvent[]>; selectedDay: Date; onMonthChange: (month: Date) => void; onSelect: (day: Date) => void }) {
  const first = new Date(month.getFullYear(), month.getMonth(), 1); const start = new Date(first); start.setDate(1 - first.getDay()); const days = Array.from({ length: 42 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return day; }); const today = dateKey(new Date());
  return <section className="month-calendar"><header><button aria-label="Mês anterior" onClick={() => onMonthChange(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><h2>{month.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })}</h2><button aria-label="Próximo mês" onClick={() => onMonthChange(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></header><div className="calendar-weekdays">{weekdays.map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{days.map(day => { const key = dateKey(day), dayEvents = events[key] ?? [], muted = day.getMonth() !== month.getMonth(); return <button key={key} className={`calendar-day${muted ? " muted" : ""}${key === today ? " today" : ""}${key === dateKey(selectedDay) ? " selected" : ""}`} onClick={() => onSelect(day)}><span>{day.getDate()}</span><div>{dayEvents.slice(0, 2).map(event => <small className={event.type.toLowerCase()} key={event.id}>{event.title}</small>)}{dayEvents.length > 2 && <small className="more">+{dayEvents.length - 2} mais</small>}</div></button>; })}</div></section>;
}

function EventForm({ editing, defaultDate, onCancel, onSaved }: { editing: CalendarEvent | null; defaultDate: string; onCancel: () => void; onSaved: () => void }) { const [message, setMessage] = useState(""), [loading, setLoading] = useState(false); const { track } = useCrudFeedback(); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget), start = String(form.get("startsAt")), end = String(form.get("endsAt")); setLoading(true); try { const response = await track(fetch(`${apiUrl}/api/events${editing ? `/${editing.id}` : ""}`, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify({ title: form.get("title"), description: form.get("description"), type: form.get("type"), startsAt: new Date(start).toISOString(), endsAt: end ? new Date(end).toISOString() : null, location: form.get("location") || null, link: form.get("link") || null }) })), data = await response.json(); if (!response.ok) throw new Error(data.message); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível salvar."); } finally { setLoading(false); } } return <form className="event-form" onSubmit={submit} key={editing?.id ?? defaultDate}><label>Título<input name="title" required defaultValue={editing?.title} /></label><label>Categoria<select name="type" defaultValue={editing?.type ?? "EVENT"}><option value="EVENT">Evento</option><option value="ENTRANCE_EXAM">Vestibular</option><option value="OLYMPIAD">Olimpíada</option></select></label><label className="event-wide">Descrição<textarea name="description" required defaultValue={editing?.description} /></label><label>Início<input name="startsAt" type="datetime-local" required defaultValue={editing ? toInput(editing.startsAt) : `${defaultDate}T09:00`} /></label><label>Término <span>(opcional)</span><input name="endsAt" type="datetime-local" defaultValue={toInput(editing?.endsAt ?? null)} /></label><label>Local<input name="location" defaultValue={editing?.location ?? ""} /></label><label>Link<input name="link" type="url" defaultValue={editing?.link ?? ""} /></label><div className="event-form-actions"><button className="button button-primary" disabled={loading}>{loading ? "Salvando…" : editing ? "Salvar alterações" : "Adicionar item"}</button>{editing && <button className="plain-button" type="button" onClick={onCancel}>Cancelar</button>}</div>{message && <p className="form-message">{message}</p>}</form>; }
